services:
  swarm-manager:
    image: docker:20-dind
    privileged: true
  swarm-worker-1:
    image: docker:20-dind
    privileged: true
  swarm-worker-2:
    image: docker:20-dind
    privileged: true
  conductor:
    image: deviantony/sind-conductor:latest
    environment:
      WAIT_HOSTS: swarm-manager:2376, swarm-worker-1:2376, swarm-worker-2:2376
      WAIT_TIMEOUT: 60
      SWARM_MANAGERS: swarm-manager
      SWARM_WORKERS: swarm-worker-1,swarm-worker-2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock


