services:
  swarm-manager-1:
    image: docker:20-dind
    privileged: true
    hostname: swarm-manager-1
    ports:
      - "${AGENT_PORT:-9001}:${AGENT_PORT:-9001}"
    healthcheck:
      test: netstat -an | grep ${AGENT_PORT:-9001} > /dev/null; if [ 0 != $$? ]; then exit 1; fi;
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    networks:
      - portainer-net
  swarm-manager-2:
    image: docker:20-dind
    privileged: true
    hostname: swarm-manager-2
    networks:
      - portainer-net
  swarm-manager-3:
    image: docker:20-dind
    privileged: true
    hostname: swarm-manager-3
    networks:
      - portainer-net
  swarm-worker-1:
    image: docker:20-dind
    privileged: true
    hostname: swarm-worker-1
    networks:
      - portainer-net
  swarm-worker-2:
    image: docker:20-dind
    privileged: true
    hostname: swarm-worker-2
    networks:
      - portainer-net
  swarm-worker-3:
    image: docker:20-dind
    privileged: true
    hostname: swarm-worker-3
    networks:
      - portainer-net
  conductor:
    image: deviantony/sind-conductor:latest
    environment:
      WAIT_HOSTS: swarm-manager-1:2376, swarm-manager-2:2376, swarm-manager-3:2376, swarm-worker-1:2376, swarm-worker-2:2376, swarm-worker-3:2376
      WAIT_TIMEOUT: 90
      SWARM_MANAGERS: swarm-manager-1,swarm-manager-2,swarm-manager-3
      SWARM_WORKERS: swarm-worker-1,swarm-worker-2,swarm-worker-3
      AGENT_PORT: ${AGENT_PORT:-9001}
      AGENT_VERSION: ${AGENT_VERSION:-latest}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - portainer-net

networks:
  portainer-net:
    external:
      name: portainer-net