services:
  swarm-manager:
    image: docker:20-dind
    privileged: true
    ports:
      - "${AGENT_PORT:-9001}:${AGENT_PORT:-9001}"
    healthcheck:
      test: netstat -an | grep ${AGENT_PORT:-9001} > /dev/null; if [ 0 != $$? ]; then exit 1; fi;
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
  swarm-worker-1:
    image: docker:20-dind
    privileged: true
  swarm-worker-2:
    image: docker:20-dind
    privileged: true
  conductor:
    image: deviantony/sind-conductor:latest
    environment:
      WAIT_HOSTS: swarm-manager:2376, swarm-worker-1:2376, swarm-worker-2:2376
      WAIT_TIMEOUT: 90
      SWARM_MANAGERS: swarm-manager
      SWARM_WORKERS: swarm-worker-1,swarm-worker-2
      AGENT_PORT: ${AGENT_PORT:-9001}
      AGENT_VERSION: ${AGENT_VERSION:-latest}
      COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock


